# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: CIS | Ensure mounting of cramfs filesystem is disabled
  tags:
    - 'CIS-RHEL8-v2.0.0'
    - 'CIS-RHEL8-v2.0.0_1.1.1.1'
    - 'CISv8-4.8-IG2'
    - 'CISv8-4.8-IG3'
  block:
  - name: Configure cramfs module
    become: true
    ansible.builtin.template:
      src: 'etc/modprobe.d/cramfs.conf.j2'
      dest: '/etc/modprobe.d/cramfs.conf'
      owner: 'root'
      group: 'root'
      mode: '0644'
    when:
      - ansible_os_family in ['Debian', 'RedHat']

  - name: Unload cramfs module
    become: true
    ansible.builtin.modprobe:
      name: 'cramfs'
      state: absent
    when:
      - ansible_os_family in ['Debian', 'RedHat']
